### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Could not initialize class qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory

### ISSUE THREAD

**Issue by yanchangwei** [qunarcorp/bistoury#107]
在线debug 默认反编译获取代码始终不成功，显示agent服务日志报错：Could not initialize class qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory

java.util.ServiceConfigurationError: qunar.tc.bistoury.remoting.netty.TaskFactory: Provider qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[na:1.8.0_131]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[na:1.8.0_131]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[na:1.8.0_131]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_131]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_131]
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:699) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209) ~[guava-20.0.jar:na]
	at qunar.tc.bistoury.agent.AgentNettyClient.start(AgentNettyClient.java:74) ~[bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.initNettyClient(AgentClient.java:94) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.refreshClient(AgentClient.java:82) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.access$100(AgentClient.java:33) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient$1.run(AgentClient.java:109) [bistoury-agent-2.0.7.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory
	at sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_131]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_131]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[na:1.8.0_131]
	... 18 common frames omitted

**Comment by xleiy** [comment]
应该是rocksdb初始化失败，可以看下有没有具体的错误日志，或者启动参数添加-Dbistoury.store.db=sqlite  切换使用sqlite做存储
