### ISSUE TITLE
2.0.7版本启动很慢，需要等十几分钟后才可以正常访问？

### ISSUE THREAD

**Issue by jakey00lzj** [qunarcorp/bistoury#110]
2.0.7版本快速启动很慢(quick_start.sh)，访问 http://ip:9091  一直转圈，等了十几分钟后才刷出来网页。
然后，重启也是需要等十几分钟后。

**Comment by xleiy** [comment]
可以看下卡在什么地方，卡到十几分钟应该是不至于的

**Comment by cccy0** [comment]
同样的情况, 启动之后访问9091端口的ui访问不了 一直转圈

ui的最后日志:
`2021-03-12 02:12:17 jdbc: 
/**/Connection conn8 = DriverManager.getConnection("jdbc:h2:tcp://localhost:9092//tmp/bistoury/h2/bistoury;MODE=MYSQL;TRACE_LEVEL_SYSTEM_OUT=2;AUTO_SERVER=TRUE;", "", "");
2021-03-12 02:12:17 jdbc: 
/**/Connection conn9 = DriverManager.getConnection("jdbc:h2:tcp://localhost:9092//tmp/bistoury/h2/bistoury;MODE=MYSQL;TRACE_LEVEL_SYSTEM_OUT=2;AUTO_SERVER=TRUE;", "", "");
[2021-03-12 02:12:17 [localhost-startStop-1] INFO  org.springframework.web.context.ContextLoader:344] Root WebApplicationContext: initialization completed in 2627 ms`

proxy日志:
`2021-03-12 02:12:10 jdbc: 
/**/Connection conn8 = DriverManager.getConnection("jdbc:h2:tcp://localhost:9092//tmp/bistoury/h2/bistoury;MODE=MYSQL;TRACE_LEVEL_SYSTEM_OUT=2;AUTO_SERVER=TRUE;", "", "");
2021-03-12 02:12:10 jdbc: 
/**/Connection conn9 = DriverManager.getConnection("jdbc:h2:tcp://localhost:9092//tmp/bistoury/h2/bistoury;MODE=MYSQL;TRACE_LEVEL_SYSTEM_OUT=2;AUTO_SERVER=TRUE;", "", "");
[2021-03-12 02:12:10 [localhost-startStop-1] INFO  org.springframework.web.context.ContextLoader:344] Root WebApplicationContext: initialization completed in 7707 ms
`

agent日志:
`[02:18:07 [main] INFO q.tc.bistoury.indpendent.agent.Main:55] - Command line argument: -XX:HeapDumpPath=/opt/bistoury/bistoury-2.0.7/bistoury-agent/bin/../logs
[02:18:08 [main] INFO qunar.tc.bistoury.agent.AgentClient:77] - start refresh bistoury netty client
[02:18:11 [main] ERRORqunar.tc.bistoury.agent.Configs:73] - get proxy config error, url [http://127.0.0.1:9090/proxy/config/foragent]
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timed out to /127.0.0.1:9090 of 3000 ms
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231) ~[async-http-client-1.9.39.jar:na]
	at com.ning.http.client.providers.netty.request.NettyRequestSender.abort(NettyRequestSender.java:422) ~[async-http-client-1.9.39.jar:na]
	at com.ning.http.client.providers.netty.request.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:47) ~[async-http-client-1.9.39.jar:na]
	at com.ning.http.client.providers.netty.request.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:48) ~[async-http-client-1.9.39.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.5.Final.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_251]
Caused by: java.util.concurrent.TimeoutException: Request timed out to /127.0.0.1:9090 of 3000 ms
	... 7 common frames omitted
[02:18:11 [main] INFO qunar.tc.bistoury.agent.AgentClient:80] - finish get bistoury proxy config, null
`

**Comment by zoom-youliang** [comment]
在`JAVA_OPTS`中加入 `-Djava.security.egd=file:/dev/./urandom`

**Comment by fishandsheep** [comment]
我的云服务器也会卡十几分钟，日志和上面的一样，但我用wsl2本地测试就秒开，没有卡顿问题，不知道是不是系统问题。
云服务器环境变量
`java -version`
> openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode)

**Comment by fishandsheep** [comment]
@jakey00lzj  我测试过了，先stop bistoury再杀掉应用，然后start会卡个10几分钟，先杀掉服务再stop bistoury，然后start就会秒启动，可能是某些服务进程被占用的原因 😀
