### ISSUE TITLE
build打包，单独启动bistoury-proxy.sh这个，报错

### ISSUE THREAD

**Issue by edagarli** [qunarcorp/bistoury#111]
```
[2020-11-11 20:12:05 [localhost-startStop-1-SendThread(127.0.0.1:2181)] INFO  org.apache.zookeeper.ClientCnxn:975] Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[2020-11-11 20:12:05 [localhost-startStop-1-SendThread(127.0.0.1:2181)] WARN  org.apache.zookeeper.ClientCnxn:1102] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_151]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_151]
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
[2020-11-11 20:12:06 [localhost-startStop-1-SendThread(127.0.0.1:2181)] INFO  org.apache.zookeeper.ClientCnxn:975] Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[2020-11-11 20:12:06 [localhost-startStop-1-SendThread(127.0.0.1:2181)] WARN  org.apache.zookeeper.ClientCnxn:1102] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_151]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_151]
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]


```

**Comment by xleiy** [comment]
本地需要zk环境，默认配置的zk环境

**Comment by edagarli** [comment]
快速启动模式呢，不需要zk环境嘛？

**Comment by edagarli** [comment]
@xleiy

**Comment by xleiy** [comment]
快速启动模式，依赖的是在本地的/tmp/bistoury/proxy.conf文件，里面存储了需要从zk上获取的信息。可以看下[qunar.tc.bistoury.serverside.common.ZKClientCache#getZkClient](https://github.com/qunarcorp/bistoury/blob/master/bistoury-serverside-common/src/main/java/qunar/tc/bistoury/serverside/common/ZKClientCache.java#L54)
