### ISSUE TITLE
在线调试jdk11 版本项目，断点添加失败

### ISSUE THREAD

**Issue by zhaofanfan2019** [qunarcorp/bistoury#116]
具体异常和调用栈
java.lang.UnsupportedOperationException: This feature requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150) ~[asm-7.0.jar:7.0]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:541) ~[asm-7.0.jar:7.0]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391) ~[asm-7.0.jar:7.0]
	at qunar.tc.bistoury.instrument.client.location.ClassResourcesIndexer.lazyIndexByDirectoryId(ClassResourcesIndexer.java:460) ~[bistoury-instrument-client-2.0.7.jar:na]
	at qunar.tc.bistoury.instrument.client.location.ClassResourcesIndexer.lazyIndexBySourceDirectory(ClassResourcesIndexer.java:409) ~[bistoury-instrument-client-2.0.7.jar:na]
	at qunar.tc.bistoury.instrument.client.location.ClassResourcesIndexer.mapSourceFile(ClassResourcesIndexer.java:290) ~[bistoury-instrument-client-2.0.7.jar:na]
	at qunar.tc.bistoury.instrument.client.location.ClassPathLookup.resolveSourceLocation(ClassPathLookup.java:191) ~[bistoury-instrument-client-2.0.7.jar:na]
	at qunar.tc.bistoury.instrument.client.debugger.DefaultDebugger.doRegisterBreakpoint(DefaultDebugger.java:147) ~[bistoury-instrument-client-2.0.7.jar:na]
	at qunar.tc.bistoury.instrument.client.debugger.DefaultDebugger.registerBreakpoint(DefaultDebugger.java:96) ~[bistoury-instrument-client-2.0.7.jar:na]
	at qunar.tc.bistoury.attach.arthas.debug.QDebugClient.registerBreakpoint(QDebugClient.java:71) ~[bistoury-attach-arthas-2.0.7.jar:na]
	at qunar.tc.bistoury.attach.arthas.debug.QDebugAddCommand.process(QDebugAddCommand.java:78) ~[bistoury-attach-arthas-2.0.7.jar:na]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.process(AnnotatedCommandImpl.java:82) ~[arthas-core-3.1.4.jar:3.1.4]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl.access$100(AnnotatedCommandImpl.java:18) ~[arthas-core-3.1.4.jar:3.1.4]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:111) ~[arthas-core-3.1.4.jar:3.1.4]
	at com.taobao.arthas.core.shell.command.impl.AnnotatedCommandImpl$ProcessHandler.handle(AnnotatedCommandImpl.java:108) ~[arthas-core-3.1.4.jar:3.1.4]
	at com.taobao.arthas.core.shell.system.impl.QProcessImpl$CommandProcessTask.run(QProcessImpl.java:370) ~[bistoury-attach-arthas-2.0.7.jar:3.1.4]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

**Comment by zhaofanfan2019** [comment]
我升级下ASM试试

**Comment by zhaofanfan2019** [comment]
![图片](https://user-images.githubusercontent.com/49738859/105833640-742a5880-6004-11eb-8221-1f5256384a70.png)
改下这个就解决了

**Comment by wikiwikiwiki** [comment]
> 我升级下ASM试试

要不提个pr

**Comment by skt-shinyruo** [comment]
Hi，可以留个联系方式吗？想请教一下JDK11的部署问题
QQ：1654388696
