### ISSUE TITLE
是否支持东方通中间件中部署的应用

### ISSUE THREAD

**Issue by conghairui** [qunarcorp/bistoury#156]
是否支持东方通中间件中部署的应用，东方通的应用点主机信息时报如下错误：
`[10:44:11 [bistoury-agent-netty-thread-1] QTraceId[] INFO  q.t.b.remoting.netty.RequestHandler] - agent receive request: id=220620.104411.9.1.183.120.18270.139592, sourceIp=/9.1.183.120:9880, code=301
[10:44:11 [bistoury-agent-netty-thread-1] QTraceId[] INFO  q.t.b.agent.common.pid.PidUtils] - get pid by PidBySystemPropertyHandler success, pid is 13974
[10:44:11 [bistoury-agent-netty-thread-1] QTraceId[] INFO  q.t.b.remoting.netty.TaskProcessor] - receive host command, id [220620.104411.9.1.183.120.18270.139592], command [13974]
[10:44:12 [log-agent-exec-0] QTraceId[] ERROR q.t.b.c.host.VirtualMachineUtil] - attach to tomcat vm error 
java.io.IOException: ???????
	at sun.tools.attach.LinuxVirtualMachine.sendQuitTo(Native Method) ~[tools.jar:na]
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:91) ~[tools.jar:na]
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63) ~[tools.jar:na]
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208) ~[tools.jar:na]
	at qunar.tc.bistoury.commands.host.VirtualMachineUtil.connect(VirtualMachineUtil.java:54) ~[bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask.init(HostTask.java:82) [bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask.access$000(HostTask.java:49) [bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask$1.call(HostTask.java:111) [bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask$1.call(HostTask.java:107) [bistoury-commands-2.0.6.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) [guava-20.0.jar:na]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) [guava-20.0.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) [guava-20.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
[10:44:12 [log-agent-exec-0] QTraceId[] ERROR q.tc.bistoury.commands.host.HostTask] - get MXBean error
java.lang.RuntimeException: Cannot perf data for process 13974 - java.io.IOException: 0503080804¨?0804
	at com.vip.vjtools.vjtop.data.PerfData.connect(PerfData.java:32) ~[vjtop-1.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask.init(HostTask.java:83) ~[bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask.access$000(HostTask.java:49) ~[bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask$1.call(HostTask.java:111) [bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask$1.call(HostTask.java:107) [bistoury-commands-2.0.6.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) [guava-20.0.jar:na]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) [guava-20.0.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) [guava-20.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
[10:44:12 [log-agent-exec-1] QTraceId[] ERROR q.t.b.remoting.netty.TaskProcessor] - host command error, id [220620.104411.9.1.183.120.18270.139592], command [13974]
java.lang.RuntimeException: java.lang.RuntimeException: Cannot perf data for process 13974 - java.io.IOException: 0503080804¨?0804
	at qunar.tc.bistoury.commands.host.HostTask$1.call(HostTask.java:123) ~[bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask$1.call(HostTask.java:107) ~[bistoury-commands-2.0.6.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111) ~[guava-20.0.jar:na]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58) ~[guava-20.0.jar:na]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75) ~[guava-20.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
Caused by: java.lang.RuntimeException: Cannot perf data for process 13974 - java.io.IOException: 0503080804¨?0804
	at com.vip.vjtools.vjtop.data.PerfData.connect(PerfData.java:32) ~[vjtop-1.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask.init(HostTask.java:83) ~[bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask.access$000(HostTask.java:49) ~[bistoury-commands-2.0.6.jar:na]
	at qunar.tc.bistoury.commands.host.HostTask$1.call(HostTask.java:111) ~[bistoury-commands-2.0.6.jar:na]
	... 7 common frames omitted
[10:53:59 [bistoury-agent-netty-thread-1] QTraceId[] INFO  q.t.b.remoting.netty.RequestHandler] - agent receive request: id=220620.105359.9.1.183.120.18270.139751, sourceIp=/9.1.183.120:9880, code=1
[10:53:59 [bistoury-agent-netty-thread-1] QTraceId[] INFO  q.t.b.commands.MetaRefreshProcessor] - meta refresh data receive, {heapJMapHistoOn=false, agent.push.interval.min=1, app.config.exclusion.file.equal=web.xml, agent.refresh.interval.min=10, tomcat.command=/home/java/default/bin/java, port=28080, app.config.exclusion.file.suffix=class,vm,css,js,vue,ts,jsp,sql,jar, cpuJStackOn=false, debug.json.limit.kb=10240, tomcat.user=tomcat}
[11:03:59 [bistoury-agent-netty-thread-1] QTraceId[] INFO  q.t.b.remoting.netty.RequestHandler] - agent receive request: id=220620.110359.9.1.183.120.18270.139873, sourceIp=/9.1.183.120:9880, code=1
[11:03:59 [bistoury-agent-netty-thread-1] QTraceId[] INFO  q.t.b.commands.MetaRefreshProcessor] - meta refresh data receive, {heapJMapHistoOn=false, agent.push.interval.min=1, app.config.exclusion.file.equal=web.xml, agent.refresh.interval.min=10, tomcat.command=/home/java/default/bin/java, port=28080, app.config.exclusion.file.suffix=class,vm,css,js,vue,ts,jsp,sql,jar, cpuJStackOn=false, debug.json.limit.kb=10240, tomcat.user=tomcat}
`

**Comment by xleiy** [comment]
这个是jvm attach不上去，异常那里你这是一串问号，具体原因可以再看下。可能是获取的pid不对，可以检查下；也有可能是用户权限问题，你用相同用户直接执行jstack看下。

**Comment by conghairui** [comment]
> 这个是jvm attach不上去，异常那里你这是一串问号，具体原因可以再看下。可能是获取的pid不对，可以检查下；也有可能是用户权限问题，你用相同用户直接执行jstack看下。

感谢回复，支持东方通中间件，我这个是用户权限问题
