### ISSUE TITLE
启动后获取代理失败

### ISSUE THREAD

**Issue by xipeng156** [qunarcorp/bistoury#166]
辛苦大神指点部署问题
启动时修改9090端口至9093（9090被其他服务占用），修改方案为
`
解压缩目录/bistoury-proxy-bin/conf/server.properties中的tomcat.port值和quick_start.sh中PROXY_TOMCAT_PORT的值以及bistoury-agent-bin/bin/bistoury-agent-env.sh中的BISTOURY_PROXY_HOST的值
`
启动命令为：
 ./quick_start.sh -p 10000 -i 192.168.1.7 -l /home/kylin/xxxxxx/bistoury/bistoury-2.0.7/tmp start
报错为获取映射失败（访问127.0.0.1超时）和spi加载cpu插件没有扫描到，具体报错信息如下：
`
[10:47:56 [main] ERRORqunar.tc.bistoury.agent.Configs:73] - get proxy config error, url [http://127.0.0.1:9093/proxy/config/foragent]
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timed out to /127.0.0.1:9093 of 3000 ms
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231) ~[async-http-client-1.9.39.jar:na]
	at com.ning.http.client.providers.netty.request.NettyRequestSender.abort(NettyRequestSender.java:422) ~[async-http-client-1.9.39.jar:na]
	at com.ning.http.client.providers.netty.request.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:47) ~[async-http-client-1.9.39.jar:na]
	at com.ning.http.client.providers.netty.request.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:48) ~[async-http-client-1.9.39.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.5.Final.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_282]
Caused by: java.util.concurrent.TimeoutException: Request timed out to /127.0.0.1:9093 of 3000 ms
	... 7 common frames omitted
[10:47:56 [main] INFO qunar.tc.bistoury.agent.AgentClient:80] - finish get bistoury proxy config, null
[10:48:56 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:77] - start refresh bistoury netty client
[10:48:59 [bistoury-agent-failover-thread-1] ERRORqunar.tc.bistoury.agent.Configs:73] - get proxy config error, url [http://127.0.0.1:9093/proxy/config/foragent]
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timed out to /127.0.0.1:9093 of 3000 ms
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231) ~[async-http-client-1.9.39.jar:na]
	at com.ning.http.client.providers.netty.request.NettyRequestSender.abort(NettyRequestSender.java:422) ~[async-http-client-1.9.39.jar:na]
	at com.ning.http.client.providers.netty.request.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:47) ~[async-http-client-1.9.39.jar:na]
	at com.ning.http.client.providers.netty.request.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:48) ~[async-http-client-1.9.39.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369) ~[netty-3.10.5.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.5.Final.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]
Caused by: java.util.concurrent.TimeoutException: Request timed out to /127.0.0.1:9093 of 3000 ms
	... 7 common frames omitted
[10:48:59 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:80] - finish get bistoury proxy config, null
[10:49:59 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:77] - start refresh bistoury netty client
[10:50:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:80] - finish get bistoury proxy config, ProxyConfig{ip='192.168.1.7', port=9880, heartbeatSec=30}
[10:50:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:88] - refresh bistoury netty client fail
java.util.ServiceConfigurationError: qunar.tc.bistoury.remoting.netty.TaskFactory: Provider qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[na:1.8.0_282]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_282]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_282]
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:699) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209) ~[guava-20.0.jar:na]
	at qunar.tc.bistoury.agent.AgentNettyClient.start(AgentNettyClient.java:74) ~[bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.initNettyClient(AgentClient.java:94) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.refreshClient(AgentClient.java:82) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.access$100(AgentClient.java:33) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient$1.run(AgentClient.java:109) [bistoury-agent-2.0.7.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_282]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]
Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni4422187846468870441.so: /tmp/librocksdbjni4422187846468870441.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_282]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934) ~[na:1.8.0_282]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817) ~[na:1.8.0_282]
	at java.lang.Runtime.load0(Runtime.java:810) ~[na:1.8.0_282]
	at java.lang.System.load(System.java:1088) ~[na:1.8.0_282]
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78) ~[rocksdbjni-5.17.2.jar:na]
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56) ~[rocksdbjni-5.17.2.jar:na]
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64) ~[rocksdbjni-5.17.2.jar:na]
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35) ~[rocksdbjni-5.17.2.jar:na]
	at qunar.tc.bistoury.agent.common.kv.RocksDBStoreImpl.<clinit>(RocksDBStoreImpl.java:43) ~[bistoury-agent-common-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.common.kv.KvDbWrapper.<init>(KvDbWrapper.java:42) ~[bistoury-agent-common-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.common.kv.KvDbs.<clinit>(KvDbs.java:28) ~[bistoury-agent-common-2.0.7.jar:na]
	at qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory.<clinit>(CpuTimeTaskFactory.java:44) ~[bistoury-commands-2.0.7.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_282]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[na:1.8.0_282]
	... 18 common frames omitted
[10:51:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:77] - start refresh bistoury netty client
[10:51:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:80] - finish get bistoury proxy config, ProxyConfig{ip='192.168.1.7', port=9880, heartbeatSec=30}
[10:51:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:88] - refresh bistoury netty client fail
java.util.ServiceConfigurationError: qunar.tc.bistoury.remoting.netty.TaskFactory: Provider qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[na:1.8.0_282]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_282]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_282]
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:699) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209) ~[guava-20.0.jar:na]
	at qunar.tc.bistoury.agent.AgentNettyClient.start(AgentNettyClient.java:74) ~[bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.initNettyClient(AgentClient.java:94) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.refreshClient(AgentClient.java:82) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.access$100(AgentClient.java:33) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient$1.run(AgentClient.java:109) [bistoury-agent-2.0.7.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_282]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_282]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[na:1.8.0_282]
	... 18 common frames omitted
[10:52:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:77] - start refresh bistoury netty client
[10:52:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:80] - finish get bistoury proxy config, ProxyConfig{ip='192.168.1.7', port=9880, heartbeatSec=30}
[10:52:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:88] - refresh bistoury netty client fail
java.util.ServiceConfigurationError: qunar.tc.bistoury.remoting.netty.TaskFactory: Provider qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[na:1.8.0_282]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_282]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_282]
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:699) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209) ~[guava-20.0.jar:na]
	at qunar.tc.bistoury.agent.AgentNettyClient.start(AgentNettyClient.java:74) ~[bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.initNettyClient(AgentClient.java:94) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.refreshClient(AgentClient.java:82) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.access$100(AgentClient.java:33) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient$1.run(AgentClient.java:109) [bistoury-agent-2.0.7.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_282]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_282]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[na:1.8.0_282]
	... 18 common frames omitted
[10:53:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:77] - start refresh bistoury netty client
[10:53:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:80] - finish get bistoury proxy config, ProxyConfig{ip='192.168.1.7', port=9880, heartbeatSec=30}
[10:53:00 [bistoury-agent-failover-thread-1] INFO qunar.tc.bistoury.agent.AgentClient:88] - refresh bistoury netty client fail
java.util.ServiceConfigurationError: qunar.tc.bistoury.remoting.netty.TaskFactory: Provider qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[na:1.8.0_282]
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_282]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_282]
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:699) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209) ~[guava-20.0.jar:na]
	at qunar.tc.bistoury.agent.AgentNettyClient.start(AgentNettyClient.java:74) ~[bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.initNettyClient(AgentClient.java:94) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.refreshClient(AgentClient.java:82) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient.access$100(AgentClient.java:33) [bistoury-agent-2.0.7.jar:na]
	at qunar.tc.bistoury.agent.AgentClient$1.run(AgentClient.java:109) [bistoury-agent-2.0.7.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_282]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_282]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class qunar.tc.bistoury.commands.cpujstack.CpuTimeTaskFactory
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_282]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_282]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) ~[na:1.8.0_282]
	... 18 common frames omitted

`

**Comment by fuwei199006** [comment]
这是来自QQ邮箱的自动回复邮件。
 
 来信已经收到 感谢您的来信  付威
