### ISSUE TITLE
docker部署agent时报错

### ISSUE THREAD

**Issue by purplewe** [qunarcorp/bistoury#61]
- bistoury-agent的log报错信息
```java
[19:19:26 [cpu-jstack-task-thread-1] QTraceId[] ERROR q.t.b.a.task.cpujstack.TaskRunner] - cpu jstack tast run error
java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
	at qunar.tc.bistoury.agent.task.cpujstack.JStackPidExecutor.execute(JStackPidExecutor.java:42) ~[bistoury-agent-task-2.0.6.jar:na]
	at qunar.tc.bistoury.agent.task.cpujstack.TaskRunner.doRun(TaskRunner.java:112) ~[bistoury-agent-task-2.0.6.jar:na]
	at qunar.tc.bistoury.agent.task.cpujstack.TaskRunner.run(TaskRunner.java:85) ~[bistoury-agent-task-2.0.6.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:623) [guava-20.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_111]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_111]
	... 11 common frames omitted
```
- 问题由来
我的应用和agent部署在同一个docker容器中，但是当proxy连接agent的时候报错如上，请问是哪方面的问题。:worried:

**Comment by xleiy** [comment]
- 你检查下你运行agent是用的jre还是jdk啊，bistoury是需要使用jdk的。
- 目前发布的版本仅支持jdk1.7和jdk1.8，java9及之后的版本需要等到下个版本

**Comment by purplewe** [comment]
非常感谢:smile:
确实用了jre来运行
