### ISSUE TITLE
启动agent报错

### ISSUE THREAD

**Issue by lujingya-dev** [qunarcorp/bistoury#67]
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106) ~[tools.jar:na]
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63) ~[tools.jar:na]
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208) ~[tools.jar:na]
        at qunar.tc.bistoury.agent.task.cpujstack.JStackPidExecutor.execute(JStackPidExecutor.java:42) ~[bistoury-agent-task-2.0.6.jar:na]
        at qunar.tc.bistoury.agent.task.cpujstack.TaskRunner.doRun(TaskRunner.java:112) [bistoury-agent-task-2.0.6.jar:na]
        at qunar.tc.bistoury.agent.task.cpujstack.TaskRunner.run(TaskRunner.java:85) [bistoury-agent-task-2.0.6.jar:na]
        at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:623) [guava-20.0.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

**Comment by wenbeicai** [comment]
看一下是不是因为agent进程的用户和应用进程的用户不相同，如果不是，改成相同的用户再看。如果是相同的，发一下详细的agent日志文件。
