### ISSUE TITLE
netty启动的web程序，不能使用吗？

### ISSUE THREAD

**Issue by mydq** [qunarcorp/bistoury#92]
Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: can not find lib class, [org.springframework.web.servlet.DispatcherServlet]
        at qunar.tc.bistoury.instrument.agent.AgentBootstrap2.main(AgentBootstrap2.java:280)
        at qunar.tc.bistoury.instrument.agent.AgentBootstrap2.agentmain(AgentBootstrap2.java:90)
        ... 6 more
Caused by: java.lang.IllegalStateException: can not find lib class, [org.springframework.web.servlet.DispatcherServlet]
        at qunar.tc.bistoury.instrument.agent.AgentBootstrap2.findLibClass(AgentBootstrap2.java:149)
        at qunar.tc.bistoury.instrument.agent.AgentBootstrap2.findUserClassLoader(AgentBootstrap2.java:127)
        at qunar.tc.bistoury.instrument.agent.AgentBootstrap2.loadOrDefineClassLoader(AgentBootstrap2.java:120)
        at qunar.tc.bistoury.instrument.agent.AgentBootstrap2.getClassLoader(AgentBootstrap2.java:107)
        at qunar.tc.bistoury.instrument.agent.AgentBootstrap2.main(AgentBootstrap2.java:254)
        ... 7 more
Agent failed to start!

**Comment by xleiy** [comment]
[agent attach时加载初始化类失败](https://github.com/qunarcorp/bistoury/blob/master/docs/cn/FAQ.md#agent-attach%E6%97%B6%E5%8A%A0%E8%BD%BD%E5%88%9D%E5%A7%8B%E5%8C%96%E7%B1%BB%E5%A4%B1%E8%B4%A5)

**Comment by mydq** [comment]
谢谢发自我的华为手机-------- 原始邮件 --------发件人： "leix.xie" <notifications@github.com>日期： 2020年6月18日周四 16:55收件人： qunarcorp/bistoury <bistoury@noreply.github.com>抄送： mydq <cuishenzhen@126.com>, Author <author@noreply.github.com>主    题： Re: [qunarcorp/bistoury] netty启动的web程序，不能使用吗？ (#92)

agent attach时加载初始化类失败
